# Generated by Django 3.2.7 on 2022-01-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='member_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='会員番号'),
        ),
    ]
