# Generated by Django 3.2.7 on 2022-01-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='member_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='会員名'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='自己紹介文'),
        ),
    ]
