# Generated by Django 3.2.7 on 2022-01-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20220111_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='member_name',
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='本文'),
        ),
    ]
