# Generated by Django 3.2.7 on 2022-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_id',
            field=models.CharField(max_length=30, verbose_name='会員番号'),
        ),
    ]
