# Generated by Django 3.2.7 on 2022-01-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='member_id',
            field=models.CharField(default=1, max_length=20, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
