# Generated by Django 3.2.7 on 2022-01-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_id',
            field=models.CharField(max_length=20, verbose_name='会員番号'),
        ),
    ]
