# Generated by Django 3.2.7 on 2022-02-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='会員番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='member_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='メンバータイプ'),
        ),
    ]
