# Generated by Django 3.2.7 on 2022-02-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220208_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_type',
            field=models.IntegerField(default=1, verbose_name='メンバータイプ'),
            preserve_default=False,
        ),
    ]
