# Generated by Django 3.2.7 on 2022-02-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_member_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='share_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='カレンダーNo'),
        ),
    ]
