# Generated by Django 3.2.7 on 2022-02-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_share_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='share_no',
        ),
    ]
