# Generated by Django 3.2.7 on 2022-02-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_customuser_share_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='メンバータイプ'),
        ),
    ]
