# Generated by Django 3.2.7 on 2022-01-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像')),
            ],
            options={
                'verbose_name_plural': 'House',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='部屋番号')),
                ('room_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='部屋名')),
                ('persons', models.IntegerField(blank=True, default=0, null=True, verbose_name='大人 - 人数')),
                ('kids', models.IntegerField(blank=True, default=0, null=True, verbose_name='子供 - 人数')),
                ('size', models.IntegerField(blank=True, default=0, null=True, verbose_name='部屋のサイズ')),
                ('Queen_bed', models.IntegerField(blank=True, default=0, null=True, verbose_name='クイーンベッド')),
                ('Double_bed', models.IntegerField(blank=True, default=0, null=True, verbose_name='ダブルベッド')),
                ('Single_Bed', models.IntegerField(blank=True, default=0, null=True, verbose_name='シングルベッド')),
                ('smoking', models.BooleanField(default=False, verbose_name='喫煙')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='部屋画像メイン')),
                ('in_date', models.DateField(blank=True, null=True, verbose_name='チェックイン')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
    ]
