# Generated by Django 3.2.7 on 2022-03-17 01:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100, unique=True, verbose_name='店舗')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所')),
                ('tel', models.CharField(blank=True, max_length=100, null=True, verbose_name='電話番号')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像')),
            ],
            options={
                'verbose_name_plural': 'House',
            },
        ),
        migrations.CreateModel(
            name='RFourCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(verbose_name='no')),
                ('no_sub', models.IntegerField(verbose_name='no_sub')),
                ('Jan', models.DateField(blank=True, null=True, verbose_name='1月')),
                ('Feb', models.DateField(blank=True, null=True, verbose_name='2月')),
                ('Mar', models.DateField(blank=True, null=True, verbose_name='3月')),
                ('Apr', models.DateField(blank=True, null=True, verbose_name='4月')),
                ('May', models.DateField(blank=True, null=True, verbose_name='5月')),
                ('Jun', models.DateField(blank=True, null=True, verbose_name='6月')),
                ('Jul', models.DateField(blank=True, null=True, verbose_name='7月')),
                ('Aug', models.DateField(blank=True, null=True, verbose_name='8月')),
                ('Sep', models.DateField(blank=True, null=True, verbose_name='9月')),
                ('Oct', models.DateField(blank=True, null=True, verbose_name='10月')),
                ('Nov', models.DateField(blank=True, null=True, verbose_name='11月')),
                ('Dec', models.DateField(blank=True, null=True, verbose_name='12月')),
            ],
            options={
                'verbose_name_plural': 'RFourCalendar',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('Ticket_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='チケット番号')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('expiry', models.DateField(verbose_name='有効期限')),
                ('ticket_status', models.BooleanField(default=False, verbose_name='利用権限')),
                ('proprietary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name_plural': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='部屋番号')),
                ('room_name', models.CharField(max_length=30, null=True, verbose_name='部屋名')),
                ('persons', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='大人 - 人数')),
                ('kids', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='子供 - 人数')),
                ('size', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='部屋のサイズ')),
                ('futon', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='布団の数')),
                ('Queen_bed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='クイーンベッド')),
                ('semi_Double_bed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='セミダブルベッド')),
                ('Double_bed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ダブルベッド')),
                ('Single_Bed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='シングルベッド')),
                ('smoking', models.BooleanField(default=False, verbose_name='喫煙')),
                ('open_bath', models.BooleanField(default=False, verbose_name='露天風呂')),
                ('corner_room', models.BooleanField(default=False, verbose_name='角部屋')),
                ('ja_style', models.BooleanField(default=False, verbose_name='和室')),
                ('we_style', models.BooleanField(default=False, verbose_name='洋室')),
                ('dog', models.BooleanField(default=False, verbose_name='介助犬')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='部屋画像メイン')),
                ('room_active', models.BooleanField(default=False, verbose_name='アクティブ')),
                ('room_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格')),
                ('house_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.house')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Representative_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='代表者名')),
                ('reserve_date', models.DateField()),
                ('reserve_status', models.IntegerField(default=1, verbose_name='予約ステータス')),
                ('Ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.ticket')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name_plural': 'Reserve',
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='チケット番号')),
                ('date', models.DateField(verbose_name='日付')),
                ('used', models.BooleanField(default=False, verbose_name='使用済')),
                ('cal_active', models.BooleanField(default=False, verbose_name='アクティブ')),
                ('member_id', models.ForeignKey(default='不明', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name_plural': 'Calendar',
            },
        ),
    ]
