# Generated by Django 3.2.7 on 2022-02-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Ticket_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='チケット番号'),
        ),
    ]
