# Generated by Django 3.2.7 on 2022-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(max_length=40, verbose_name='部屋タイプ'),
        ),
    ]
