# Generated by Django 3.2.7 on 2022-02-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='house',
            constraint=models.UniqueConstraint(fields=('house_name',), name='unique_constraint'),
        ),
    ]
