# Generated by Django 3.2.7 on 2022-01-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='in_date',
        ),
    ]
