# Generated by Django 3.2.7 on 2022-03-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='order_number',
            field=models.IntegerField(default=1, unique=True, verbose_name='注文番号'),
            preserve_default=False,
        ),
    ]
