# Generated by Django 3.2.7 on 2022-01-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='House',
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name_plural': 'House'},
        ),
    ]
