# Generated by Django 3.2.7 on 2022-02-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='Representative_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='代表者名'),
        ),
    ]
