# Generated by Django 3.2.7 on 2022-04-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='check_in_week',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='check_out_week',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='processing_week',
        ),
    ]
