# Generated by Django 3.2.7 on 2022-01-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220113_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='店舗')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
    ]
