# Generated by Django 3.2.7 on 2022-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reserve_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='order_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='注文番号'),
        ),
    ]
