# Generated by Django 3.2.7 on 2022-02-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_house_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='house_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.house'),
        ),
    ]
