# Generated by Django 3.2.7 on 2022-02-16 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0002_reserve_representative_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='member_id',
            field=models.ForeignKey(default='不明', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
