# Generated by Django 3.2.7 on 2022-02-07 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reserve_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='futon',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='布団の数'),
        ),
    ]
