# Generated by Django 3.2.7 on 2022-03-17 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_giveticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='価格'),
        ),
    ]
