# Generated by Django 3.2.7 on 2022-02-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_calendar_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='used',
            field=models.BooleanField(default=False, verbose_name='使用済'),
        ),
    ]
