# Generated by Django 3.2.7 on 2022-03-24 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_alter_reserve_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.customuser', verbose_name='所有者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='order_number',
            field=models.CharField(max_length=30, verbose_name='注文番号'),
        ),
    ]
