# Generated by Django 3.2.7 on 2022-01-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='部屋画像メイン'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=1, max_length=10, verbose_name='部屋名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='部屋番号'),
        ),
    ]
