# Generated by Django 3.2.7 on 2022-03-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_room_room_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
