# Generated by Django 3.2.7 on 2022-01-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20220113_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='喫煙'),
        ),
    ]
