# Generated by Django 3.2.7 on 2022-02-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_calendar_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='cal_active',
            field=models.BooleanField(default=False, verbose_name='アクティブ'),
        ),
    ]
