# Generated by Django 3.2.7 on 2022-01-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_room_smoking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='kids',
            field=models.IntegerField(default=0, verbose_name='子供 - 人数'),
        ),
        migrations.AddField(
            model_name='room',
            name='persons',
            field=models.IntegerField(default=0, verbose_name='大人 - 人数'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='部屋名'),
        ),
    ]
