# Generated by Django 3.2.7 on 2022-03-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_calendar_cal_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFourCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='no')),
                ('Jan', models.DateField(blank=True, null=True, verbose_name='1月')),
                ('Feb', models.DateField(blank=True, null=True, verbose_name='2月')),
                ('Mar', models.DateField(blank=True, null=True, verbose_name='3月')),
                ('Apr', models.DateField(blank=True, null=True, verbose_name='4月')),
                ('May', models.DateField(blank=True, null=True, verbose_name='5月')),
                ('Jun', models.DateField(blank=True, null=True, verbose_name='6月')),
                ('Jul', models.DateField(blank=True, null=True, verbose_name='7月')),
                ('Aug', models.DateField(blank=True, null=True, verbose_name='8月')),
                ('Sep', models.DateField(blank=True, null=True, verbose_name='9月')),
                ('Oct', models.DateField(blank=True, null=True, verbose_name='10月')),
                ('Nov', models.DateField(blank=True, null=True, verbose_name='11月')),
                ('Dec', models.DateField(blank=True, null=True, verbose_name='12月')),
            ],
            options={
                'verbose_name_plural': 'RFourCalendar',
            },
        ),
    ]
