# Generated by Django 3.2.7 on 2022-03-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rfourcalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfourcalendar',
            name='no',
            field=models.FloatField(blank=True, null=True, verbose_name='no'),
        ),
    ]
