# Generated by Django 3.2.7 on 2022-03-17 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_roomtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_type',
            field=models.CharField(max_length=20, verbose_name='部屋タイプ'),
        ),
    ]
