# Generated by Django 3.2.7 on 2022-01-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20220113_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='部屋のサイズ'),
        ),
        migrations.AlterField(
            model_name='room',
            name='kids',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='子供 - 人数'),
        ),
        migrations.AlterField(
            model_name='room',
            name='persons',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='大人 - 人数'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='部屋番号'),
        ),
    ]
