# Generated by Django 3.2.7 on 2022-02-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_dailyviews_movie'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='house',
            name='unique_constraint',
        ),
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='店舗'),
        ),
    ]
