# Generated by Django 3.2.7 on 2022-01-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20220113_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Double_bed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ダブルベッド'),
        ),
        migrations.AddField(
            model_name='room',
            name='Queen_bed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='クイーンベッド'),
        ),
        migrations.AddField(
            model_name='room',
            name='Single_Bed',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='シングルベッド'),
        ),
    ]
