# Generated by Django 3.2.7 on 2022-03-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_rfourcalendar_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfourcalendar',
            name='no_sub',
            field=models.IntegerField(blank=True, null=True, verbose_name='no_sub'),
        ),
        migrations.AlterField(
            model_name='rfourcalendar',
            name='no',
            field=models.IntegerField(blank=True, null=True, verbose_name='no'),
        ),
    ]
