# Generated by Django 3.2.7 on 2022-03-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20220317_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
