# Generated by Django 3.2.7 on 2022-01-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20220113_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='部屋名'),
        ),
    ]
