# Generated by Django 3.2.7 on 2022-02-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_reserve_member_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserve',
            table='reserve',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
