# Generated by Django 3.2.7 on 2022-03-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20220308_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfourcalendar',
            name='no',
            field=models.IntegerField(verbose_name='no'),
        ),
        migrations.AlterField(
            model_name='rfourcalendar',
            name='no_sub',
            field=models.IntegerField(verbose_name='no_sub'),
        ),
    ]
