# Generated by Django 3.2.7 on 2022-01-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='in_date',
            field=models.DateField(auto_now=True),
        ),
    ]
