# Generated by Django 3.2.7 on 2022-02-15 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20220214_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reserve',
            table=None,
        ),
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
    ]
