# Generated by Django 3.2.7 on 2022-03-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_auto_20220308_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='member_id',
        ),
    ]
