# Generated by Django 3.2.7 on 2022-01-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_room_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='in_date',
            field=models.DateField(blank=True, null=True, verbose_name='チェックイン'),
        ),
    ]
