# Generated by Django 3.2.7 on 2022-03-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_remove_reserve_member_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
    ]
