# Generated by Django 3.2.7 on 2022-01-14 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_room_in_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='in_date',
            new_name='set_date',
        ),
    ]
