# Generated by Django 3.2.7 on 2022-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserve_status',
            field=models.IntegerField(default=1, verbose_name='予約ステータス'),
        ),
    ]
