# Generated by Django 3.2.7 on 2022-01-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_rename_in_date_room_set_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='set_date',
            new_name='in_date',
        ),
    ]
