# Generated by Django 3.2.7 on 2022-03-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20220314_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiveTicket',
        ),
    ]
