# Generated by Django 3.2.7 on 2022-03-14 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0014_delete_giveticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_date', models.DateField(verbose_name='贈与日')),
                ('give_member_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='譲る会員番号')),
                ('ticket_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.ticket')),
            ],
            options={
                'verbose_name_plural': 'GiveTicket',
            },
        ),
    ]
