# Generated by Django 3.2.7 on 2022-01-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_auto_20220117_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='set_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='task',
        ),
        migrations.AddField(
            model_name='room',
            name='in_date',
            field=models.DateField(blank=True, null=True, verbose_name='チェックイン'),
        ),
    ]
