# Generated by Django 3.2.7 on 2022-01-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20220117_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='in_date',
            new_name='set_date',
        ),
        migrations.AddField(
            model_name='room',
            name='task',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='やること'),
        ),
    ]
